# Generated by Django 5.2.6 on 2025-09-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the contact', max_length=100)),
                ('address', models.TextField(help_text='Complete address of the contact')),
                ('profession', models.CharField(help_text='Profession or job title', max_length=100)),
                ('tel_number', models.CharField(help_text='Telephone number', max_length=20)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
    ]
