# Generated by Django 5.2.6 on 2025-11-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Medical Contact', 'verbose_name_plural': 'Medical Contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='accepts_new_patients',
            field=models.BooleanField(default=True, help_text='Whether the doctor accepts new patients'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='Unknown', help_text='City where the doctor practices', max_length=80),
        ),
        migrations.AddField(
            model_name='contact',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average consultation fee (USD)', max_digits=8),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='USA', help_text='Country', max_length=80),
        ),
        migrations.AddField(
            model_name='contact',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hospital',
            field=models.CharField(blank=True, help_text='Hospital or clinic affiliation', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the office', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the office', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Office contact number', max_length=25),
        ),
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average patient rating /5', max_digits=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='specialty',
            field=models.CharField(default='General Practice', help_text='Primary medical specialty', max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, help_text='State or province', max_length=80),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of searchable tags (procedures, languages, etc.)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, help_text='Full address for mapping and routing'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Business email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text="Doctor's full name", max_length=120),
        ),
    ]
